###Obtener productos
GET HTTP://localhost:3000/api/productos HTTP/1.1

###OBTENER PRODUCTO POR IF
GET GET HTTP://localhost:3000/api/productos/6086492d1f7fed41c7bae189 HTTP/1.1

###INSERTAT UN PRODUCTO
POST HTTP://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json

{
    "nombre": "Cable USB C",
    "precio": 20.99,
    "anio": 2020
}

###MOdificar por id
PUT HTTP://localhost:3000/api/productos/6086492d1f7fed41c7bae189 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Cable USB 3.0",
    "precio": 20.99,
    "anio": 2020
}

###Delete por ID
DELETE HTTP://localhost:3000/api/productos/6086492d1f7fed41c7bae189 HTTP/1.1
